#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.3 MB 10.3 MB/s eta 0:00:02
   ---------- ----------------------------- 3.1/12.3 MB 9.6 MB/s eta 0:00:01
   ----------------- ---------------------- 5.5/12.3 MB 10.1 MB/s eta 0:00:01
   ------------------------ --------------- 7.6/12.3 MB 10.2 MB/s eta 0:00:01
   ------------------------------- -------- 9.7/12.3 MB 10.4 MB/s eta 0:00:01
   -------------------------------------- - 11.8/12.3 MB 10.4 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 10.3 MB/s  0:00:01
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

# Create a 1D array from a Python list
ar1 = np.array([1, 2, 3, 4, 5])

print(ar1)          
print(type(ar1))    
print(ar1.shape)   
print(ar1.ndim)     
print(ar1.dtype)   


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
1
int64


In [3]:

ar2 = np.array([[1, 2, 3, 4, 5],
                [2, 3, 4, 5, 6]])

print(ar2)


print(ar2.shape)  
print(ar2.ndim)  

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)
2


In [4]:
ar1 = np.array([1, 2, 3, 4, 5])
print(ar1.shape)  

# Reshape to 1 row, 5 columns (2D)
ar2d = ar1.reshape(1, 5)
print(ar2d)        
print(ar2d.shape) 

# Reshape to 5 rows, 1 column
ar_col = ar1.reshape(5, 1)
print(ar_col)
print(ar_col.shape)  

(5,)
[[1 2 3 4 5]]
(1, 5)
[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [5]:
# np.arange(start, stop, step)  
arr = np.arange(0, 10, 2)  
print(arr)    
arr = arr.reshape(5, 1)              
print(arr)


[0 2 4 6 8]
[[0]
 [2]
 [4]
 [6]
 [8]]


In [6]:
# np.ones(shape)  
ones = np.ones((3, 4))          
print(ones)

# np.zeros(shape) 
zeros = np.zeros((3, 4))       
print(zeros)

# np.eye(n)  
identity = np.eye(3)           
print(identity)

# np.linspace(start, stop, num) 
lin = np.linspace(0, 1, 5)   
print(lin) 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.   0.25 0.5  0.75 1.  ]


In [7]:
## Attributes of Numpy Array
ar = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])

print("Array:\n", ar)

Array:
 [[1 2 3 4]
 [4 5 6 7]]


In [8]:
print("Shape:", ar.shape) 

Shape: (2, 4)


In [9]:
print("Number of dimensions:", ar.ndim) 

Number of dimensions: 2


In [10]:
print("Size (number of elements):", ar.size) 

Size (number of elements): 8


In [11]:
print("Data type:", ar.dtype) 

Data type: int64


In [12]:
print("Item size (in bytes):", ar.itemsize)  

Item size (in bytes): 8


In [13]:
print("Transpose:\n", ar.T)

Transpose:
 [[1 4]
 [2 5]
 [3 6]
 [4 7]]


In [14]:
print("Iterate over all elements, row by row:")
for element in ar.flat:
    print(element)

Iterate over all elements, row by row:
1
2
3
4
4
5
6
7


In [15]:
print("Total bytes consumed:", ar.nbytes)

Total bytes consumed: 64


In [16]:
ar1 = np.array([1, 2, 3, 4, 5])
ar2 = np.array([10, 20, 30, 40, 50])

# Element-wise operations (same index positions are paired)
print('Addition:',       ar1 + ar2)   
print('Subtraction:',    ar1 - ar2)   
print('Multiplication:', ar1 * ar2)  
print('Division:',       ar1 / ar2)   
print('Modulo:',         ar2 % ar1) 
print('Power:',          ar1 ** 2)  

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]
Modulo: [0 0 0 0 0]
Power: [ 1  4  9 16 25]


In [17]:
ar = np.array([1, 2, 3, 4, 5])

# Scalar operations (applied to every element)
print(ar + 10)    
print(ar * 3)   
print(ar ** 2)   
print(ar > 3)    
print(ar / 2)     

[11 12 13 14 15]
[ 3  6  9 12 15]
[ 1  4  9 16 25]
[False False False  True  True]
[0.5 1.  1.5 2.  2.5]


In [18]:
result = []
for x in [1,2,3,4,5]:
    result.append(x + 10)

In [19]:
result

[11, 12, 13, 14, 15]

In [20]:
result = ar + 10

In [21]:
result

array([11, 12, 13, 14, 15])

In [22]:
arr = np.array([1, 4, 9, 16, 25])

print(np.sqrt(arr))        

[1. 2. 3. 4. 5.]


In [23]:
print(np.exp(arr))    

[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]


In [24]:
print(np.log(arr))    

[0.         1.38629436 2.19722458 2.77258872 3.21887582]


In [25]:
print(np.sin(arr))    
print(np.cos(arr))    

[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
[ 0.54030231 -0.65364362 -0.91113026 -0.95765948  0.99120281]


In [26]:
arr = np.array([-1, -0.5, 0, 0.5, 1])

In [27]:
print(np.abs(arr))     
print(np.floor(arr))   
print(np.ceil(arr))

[1.  0.5 0.  0.5 1. ]
[-1. -1.  0.  0.  1.]
[-1. -0.  0.  1.  1.]


In [28]:
data = np.array([2, 4, 6, 8, 10, 12])

print(np.mean(data))  
print(np.median(data)) 
print(np.std(data))    
print(np.var(data))   
print(np.min(data))   
print(np.max(data))    
print(np.sum(data))   

7.0
7.0
3.415650255319866
11.666666666666666
2
12
42


In [29]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(np.sum(matrix))          


45


In [30]:
# axis=0 → operate DOWN the columns (result has shape of one row)
print(np.sum(matrix, axis=0))  
print(np.mean(matrix, axis=0))

[12 15 18]
[4. 5. 6.]


In [31]:
# axis=1 → operate ACROSS the rows (result has shape of one col)
print(np.sum(matrix, axis=1))  
print(np.mean(matrix, axis=1))

[ 6 15 24]
[2. 5. 8.]


In [32]:
arr = np.array([10, 20, 30, 40, 50])
#  Indices:        0   1   2   3   4   (forward)
#  Negative:      -5  -4  -3  -2  -1   (backward)

# Positive indexing (left to right, starts at 0)
print(arr[0])   
print(arr[2]) 
print(arr[4])   


10
30
50


In [33]:
# Negative indexing (right to left, starts at -1)
print(arr[-1])  
print(arr[-2])  

50
40


In [34]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

# Syntax: arr[start : stop : step]
# start: inclusive  |  stop: exclusive  |  step: stride

print(arr[1:4])   
print(arr[:3])    
print(arr[4:])    
print(arr[::2])  
print(arr[::-1])   
print(arr[1:6:2]) 


[20 30 40]
[10 20 30]
[50 60 70]
[10 30 50 70]
[70 60 50 40 30 20 10]
[20 40 60]


In [35]:
A = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12]])
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [36]:
print(A[0][0])
print(A[1][2])

1
7


In [37]:
# Single element: arr[row_index, col_index]
print(A[0, 0])   
print(A[1, 2])  

1
7


In [38]:
A = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12]])

# A[row_slice, col_slice]
print(A[0, :])             

[1 2 3 4]


In [39]:
print(A[:, 0])          

[1 5 9]


In [40]:
print(A[1:, 2:])         

[[ 7  8]
 [11 12]]


In [41]:
print(A[1:, :2])        

[[ 5  6]
 [ 9 10]]


In [42]:
print(A[1:, 1:3]) 

[[ 6  7]
 [10 11]]


In [43]:
A = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12]])

# Modify a single element
A[0, 0] = 100
print(A)  

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [44]:
# Modify a slice (entire row)
A[1, :] = 0
print(A)  

[[100   2   3   4]
 [  0   0   0   0]
 [  9  10  11  12]]


In [45]:
# Modify with condition (Boolean masking)
A[A > 5] = -1  
print(A)

[[-1  2  3  4]
 [ 0  0  0  0]
 [-1 -1 -1 -1]]


In [46]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Boolean & Logical indexing
# Step 1: Create a Boolean mask
mask = data > 5
print(mask)  

[False False False False False  True  True  True  True  True]


In [47]:
# Step 2: Use mask to filter elements
print(data[data > 5]) 

# Compound conditions (use & for AND, | for OR)
# MUST use parentheses around each condition!
print(data[(data >= 3) & (data <= 7)])   
print(data[(data < 3) | (data > 8)])    

[ 6  7  8  9 10]
[3 4 5 6 7]
[ 1  2  9 10]


In [48]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

# Select elements at specific positions
idx = [0, 2, 5, 7]
print(arr[idx])             

[10 30 60 80]


In [49]:
# 2D fancy indexing
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)

row_idx = [0, 2]
col_idx = [1, 2]
print(A[row_idx, col_idx])       

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2 9]


In [50]:
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Step 1: Calculate statistics
mu    = np.mean(data)    # 55.0
sigma = np.std(data)     # 28.72

# Step 2: Apply Z-score formula (vectorized!)
normalized = (data - mu) / sigma

print('Original:', data)
print('Normalized:', np.round(normalized, 2))


Original: [ 10  20  30  40  50  60  70  80  90 100]
Normalized: [-1.57 -1.22 -0.87 -0.52 -0.17  0.17  0.52  0.87  1.22  1.57]


In [51]:
# Set seed for reproducibility (same results every run)
np.random.seed(42)

# Uniform random floats in [0, 1)
print(np.random.rand(3, 4)) 

[[0.37454012 0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449 0.96990985]]


In [52]:

# Standard normal distribution (mean=0, std=1)
print(np.random.randn(3, 4))      

[[-0.46947439  0.54256004 -0.46341769 -0.46572975]
 [ 0.24196227 -1.91328024 -1.72491783 -0.56228753]
 [-1.01283112  0.31424733 -0.90802408 -1.4123037 ]]


In [53]:
# Random integers in [low, high)
print(np.random.randint(0, 100, (3, 4)))

[[61 61 46 61]
 [50 54 63  2]
 [50  6 20 72]]


In [54]:
# Random choice from an array
arr = np.array([10, 20, 30, 40, 50])
print(np.random.choice(arr, 3))    

[20 40 10]


In [55]:
# Shuffle an array in-place
np.random.shuffle(arr)
print(arr)  

[10 30 50 20 40]


In [56]:
# VIEW (shared memory)
a = np.array([1, 2, 3, 4, 5])
print(a)

b = a[1:4] 
b[0] = 999
print(a) 

[1 2 3 4 5]
[  1 999   3   4   5]


In [57]:
# COPY (independent)
c = a.copy()  # explicit copy
print(c)            

c[0] = 777
print(c)
print(a) 

[  1 999   3   4   5]
[777 999   3   4   5]
[  1 999   3   4   5]


In [58]:
# How to check if view or copy?
b = a[1:4]
print(b.base is a)  

c = a.copy()
print(c.base is a) 

True
False


In [59]:
# Scenario: Label student performance based on score
scores = np.array([45, 72, 88, 55, 91, 63, 38, 77, 82, 50])

# Single condition
labels = np.where(scores >= 60, 'Pass', 'Fail')
print(labels)

['Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Pass' 'Fail']


In [60]:
# Nested np.where for multiple grades
grades = np.where(scores >= 90, 'A',
         np.where(scores >= 75, 'B',
         np.where(scores >= 60, 'C',
         np.where(scores >= 45, 'D', 'F'))))
print(grades)

['D' 'C' 'B' 'D' 'A' 'C' 'F' 'B' 'B' 'D']
